feat: adiciona funcionamento da busca por gênero de filme
guifxb/projeto_flutter_4 pull request #9
Opened 2024-06-03 18:31 UTC by guifxb

feat: adiciona persistência de dados para a lista de gênero favoritos

2024-06-06 18:19 UTC, LucasTeixeiraDev commented on lib/src/presentation/home/movie_list_view.dart
> +  final CategoryRepository categoryRepository = CategoryRepository();
Se existe um cubit que é responsável por fazer o fetch dos dados então faz sentido deixar essa responsabilidade apenas no cubit.

2024-06-06 18:19 UTC, LucasTeixeiraDev commented on lib/src/presentation/home/movie_list_view.dart
> +      body: FutureBuilder<Map<String, List<MovieItem>>>(
Eu acho que aqui cabe um BlocBuilder chamando o Cubit responsável por chamar as categorias, assim você consegue validar os estados estão sendo emitidos

2024-06-06 18:24 UTC, LucasTeixeiraDev requested changes

2024-06-06 18:24 UTC, LucasTeixeiraDev commented on lib/src/data/category_repository.dart
> +  static final apiKey = Const.key;
Tem um bug nesta ApiKey

2024-06-06 18:27 UTC, LucasTeixeiraDev commented on lib/src/data/category_repository.dart
> +    final uri = Uri.http(baseUrl, path, params);
Eu acho que aqui é tem que ser https não?

2024-06-06 18:59 UTC, LucasTeixeiraDev approved these changes

2024-06-06 18:59 UTC, LucasTeixeiraDev commented on lib/src/data/model/category_list.dart
> +  Future<void> _saveToFavorites() async {
Eu acho que faz mais sentido essa classe ser um repositório de dados do que um model. E então deixar a responsabilidade de chamar no front do Cubit

2024-06-07 16:32 UTC, guifxb commented on lib/src/presentation/home/movie_list_view.dart
> +      body: FutureBuilder<Map<String, List<MovieItem>>>(
Done!

2024-06-07 16:34 UTC, merged